name: Promote current snapx demo test release version to production
on: 
  release:
    types: [published]
      
env:
  DOTNET_NET60_VERSION: 7.0.203

jobs:
  publish:
    name: Publish ${{ matrix.name }} (${{ github.ref }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: 
        include:
        - id: demoapp-linux-arm64
          rid: linux-arm64
          os: ubuntu-latest
        - id: demoapp-linux-x64
          rid: linux-x64
          os: ubuntu-latest
        - id: demoapp-win-x86
          rid: win-x86
          os: windows-latest
        - id: demoapp-win-x64
          rid: win-x64
          os: windows-latest
    steps:  
      - name: Disallow Concurrent Runs
        if: github.ref == 'refs/heads/master'
        uses: byu-oit/github-action-disallow-concurrent-runs@v2.0.2
        with:
          token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: '${{ github.ref }}'
          
      - name: Add dotnet tools to environment path
        shell: pwsh
        run: echo "${HOME}/.dotnet/tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      
      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: ${{ env.DOTNET_NET60_VERSION }}
          
      - name: Setup dotnet snapx
        shell: pwsh
        run: | 
          [xml] $xml_content = Get-Content ".\$GITHUB_WORKSPACE\Directory.Build.props";
          $snapx_version = Select-Xml -Xml $xml_content -XPath "//Project/PropertyGroup/SnapxVersion" | Select -Expand Node | Select -Expand "#text"
          dotnet tool update snapx --global --version $snapx_version

      - name: Add demoapp nuget publish feed
        shell: pwsh
        run: |
          $SourceUrl = Get-Content .snapx/update.json | ConvertFrom-Json | Select -ExpandProperty source
          dotnet nuget add source ${SourceUrl} demoapp-publish-feed            

      - name: Publish 
        shell: pwsh
        run: snapx promote ${{ matrix.name }} --api-key ${{ secrets.DEMOAPP_PUBLISH_FEED_API_KEY }} -r ${{ matrix.rid }} -c test --all --skip-installers --lock-token ${{ secrets.SNAPX_TOKEN }} --lock-retries -1 -y
